spring.application.name=tushkuna-app
# Puerto del servidor
server.port=8080

# Base de datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/tushkuna_app
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Thymeleaf
spring.thymeleaf.cache=false

# reCAPTCHA (después te explico cómo obtener estas keys)
recaptcha.site-key=6LeyI0UtAAAAAK1FW7tD3tTzDGggT6Q4vK--D24R
recaptcha.secret-key=6LeyI0UtAAAAAE5uDBhZTkXPjbE622nXDkQCsHzz
recaptcha.verify-url=https://www.google.com/recaptcha/api/siteverify